apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: staging
  name: advertisements
spec:
  replicas: 1
  selector:
    matchLabels:
      tags.datadoghq.com/env: staging
  strategy:
    canary:
      steps:
      - setWeight: 100
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: staging
        tags.datadoghq.com/version: "88330001c0f3b398fd1b2e19e672e4c657e24f7c"
    spec:
      containers:
      - image: "koheisato0714/ads-service:41601650d7aca39c382fdeb8819c02bbbab7fda9"
        name: advertisements
