apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: staging
  name: advertisements
spec:
  replicas: 1
  selector:
    matchLabels:
      tags.datadoghq.com/env: staging
  strategy:
    canary:
      steps:
      - setWeight: 100
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: staging
        tags.datadoghq.com/version: "c41dd633a83e235f01d2867c9f282824e1ad2765"
    spec:
      containers:
      - image: "koheisato-dd/ads-service:c41dd633a83e235f01d2867c9f282824e1ad2765"
        name: advertisements
