apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: prod
  name: advertisements
spec:
  replicas: 4
  selector:
    matchLabels:
      tags.datadoghq.com/env: prod
  strategy:
    canary:
      analysis:
        templates:
        - templateName: trace-error-rate
        startingStep: 1
        args:
        - {name: service-name, value: advertisements-service}
        - {name: version, value: "1d243fbf862791a0f7a75041735203e5342677cb"}
      steps:
      - setWeight: 25
      - pause: {duration: 5m}
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/version: "1d243fbf862791a0f7a75041735203e5342677cb"
    spec:
      containers:
      - image: "shocnt/ads-service:1d243fbf862791a0f7a75041735203e5342677cb"
        name: advertisements
