apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: prod
  name: advertisements
spec:
  replicas: 4
  selector:
    matchLabels:
      tags.datadoghq.com/env: prod
  strategy:
    canary:
      analysis:
        templates:
        - templateName: trace-error-rate
        startingStep: 1
        args:
        - {name: service-name, value: advertisements-service}
        - {name: version, value: "c41dd633a83e235f01d2867c9f282824e1ad2765"}
      steps:
      - setWeight: 25
      - pause: {duration: 5m}
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/version: "c41dd633a83e235f01d2867c9f282824e1ad2765"
    spec:
      containers:
      - image: "koheisato0714/ads-service:c41dd633a83e235f01d2867c9f282824e1ad2765"
        name: advertisements
