apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: development
    tags.datadoghq.com/service: advertisements-service
    app: ecommerce
  name: advertisements
spec:
  replicas: 4
  selector:
    matchLabels:
      tags.datadoghq.com/env: development
      tags.datadoghq.com/service: advertisements-service
      app: ecommerce
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 1
      steps:
      - setWeight: 25
      - pause: {}
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: development
        tags.datadoghq.com/service: advertisements-service
        tags.datadoghq.com/version: VERSION
        app: ecommerce
      annotations:
        ad.datadoghq.com/advertisements.logs: '[{"source": "python", "service": "advertisements-service"}]'
        ad.datadoghq.com/advertisements.tags: '{"team": "advertisements"}'
    spec:
      containers:
      - image: IMAGE
        imagePullPolicy: IfNotPresent
        name: advertisements
        command: ["ddtrace-run"]
        args: ["flask", "run", "--port=5002", "--host=0.0.0.0"]
        env:
          - name: FLASK_APP
            value: "ads.py"
          - name: FLASK_DEBUG
            value: "1"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: pw
                name: db-password
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_HOST
            value: "db"
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_ANALYTICS_ENABLED
            value: "true"
          - name: DD_PROFILING_ENABLED
            value: "true"
        ports:
        - containerPort: 5002
