name: Run Datadog Synthetic tests and Create PR to main

on:
  push:
    branches: [ "staging" ]

env:
  BASE_BRANCH: main
  REVIEWER: koheisato-dd

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - uses: jakejarvis/wait-action@v0.1.1
      with:
        time: '3m'
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Datadog Synthetics CI
      uses: DataDog/synthetics-ci-github-action@v0.10.0
      with:
        api_key: 3af74e80e61bc19556859de40f1a689b
        app_key: a0e35b39c667b5de11c0b14441df9321e0730814
        public_ids: '3r4-f83-ky3, gum-n39-z2p'

  create_pr:
    needs: e2e-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check PR
        id: check_pr
        run: |
          echo "count=$(gh pr list -B ${{ env.BASE_BRANCH }} -H ${{ github.ref_name }} --json 'id' -q '.[] | length')" >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.check_pr.outputs.count == '' }}
        run: gh pr create --fill -B ${{ env.BASE_BRANCH }} -r ${{ env.REVIEWER }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
